-- MySQL Script generated by MySQL Workbench
-- Sun Aug 20 14:06:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_pet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_pet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_pet` DEFAULT CHARACTER SET utf8 ;
USE `sistema_pet` ;

-- -----------------------------------------------------
-- Table `sistema_pet`.`agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`agenda` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data_entrada` DATE NOT NULL,
  `data_saida` DATE NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `situacao` VARCHAR(20) NOT NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  `observacao` VARCHAR(500) NOT NULL,
  `pet_id` INT(11) NOT NULL,
  `pessoa_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `pet_id` (`pet_id` ASC, `pessoa_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `sistema_pet`.`categoria_pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`categoria_pet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `tipo` VARCHAR(50) NOT NULL,
  `limite` INT(10) NOT NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `sistema_pet`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`estado` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema_pet`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`cidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NOT NULL,
  `estado` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1` (`estado` ASC) VISIBLE,
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado`)
    REFERENCES `sistema_pet`.`estado` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5565
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema_pet`.`contas_pagar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`contas_pagar` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(500) NOT NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  `data` DATE NOT NULL,
  `situacao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema_pet`.`contas_receber`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`contas_receber` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(200) NOT NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  `valor_restante` DECIMAL(11,2) NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  `agenda_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `agenda_id`),
  INDEX `fk_contas_receber_agenda1_idx` (`agenda_id` ASC) VISIBLE,
  CONSTRAINT `fk_contas_receber_agenda1`
    FOREIGN KEY (`agenda_id`)
    REFERENCES `sistema_pet`.`agenda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `sistema_pet`.`detalhes_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`detalhes_pagamento` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  `data_pagamento` DATE NOT NULL,
  `contas_receber_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `contas_receber_id`),
  INDEX `fk_detalhes_pagamento_contas_receber1_idx` (`contas_receber_id` ASC) VISIBLE,
  CONSTRAINT `fk_detalhes_pagamento_contas_receber1`
    FOREIGN KEY (`contas_receber_id`)
    REFERENCES `sistema_pet`.`contas_receber` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema_pet`.`email`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`email` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema_pet`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`endereco` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema_pet`.`licenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`licenca` (
  `id` INT(11) NOT NULL,
  `data_sistema` DATE NOT NULL,
  `data_licenca` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema_pet`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`telefone` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `telCelular` VARCHAR(45) NULL DEFAULT NULL,
  `telComercial` VARCHAR(45) NULL DEFAULT NULL,
  `telResidencial` VARCHAR(45) NULL DEFAULT NULL,
  `telWhatsapp` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema_pet`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`pessoa` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf_cnpj` VARCHAR(20) NULL DEFAULT NULL,
  `rg` VARCHAR(15) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `sexo` VARCHAR(10) NULL DEFAULT NULL,
  `ativo` VARCHAR(10) NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NOT NULL,
  `endereco_id` INT(11) NOT NULL,
  `email_id` INT(11) NOT NULL,
  `telefone_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `endereco_id`, `email_id`, `telefone_id`),
  INDEX `fk_pessoa_endereco1_idx` (`endereco_id` ASC) VISIBLE,
  INDEX `fk_pessoa_email1_idx` (`email_id` ASC) VISIBLE,
  INDEX `fk_pessoa_telefone1_idx` (`telefone_id` ASC) VISIBLE,
  CONSTRAINT `fk_pessoa_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `sistema_pet`.`endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_email1`
    FOREIGN KEY (`email_id`)
    REFERENCES `sistema_pet`.`email` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoa_telefone1`
    FOREIGN KEY (`telefone_id`)
    REFERENCES `sistema_pet`.`telefone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sistema_pet`.`pet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`pet` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `raca` VARCHAR(200) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `sexo` VARCHAR(200) NOT NULL,
  `veterinario` VARCHAR(200) NOT NULL,
  `observacao` VARCHAR(200) NOT NULL,
  `pessoa_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `pessoa_id`),
  INDEX `fk_pet_pessoa1_idx` (`pessoa_id` ASC) VISIBLE,
  CONSTRAINT `fk_pet_pessoa1`
    FOREIGN KEY (`pessoa_id`)
    REFERENCES `sistema_pet`.`pessoa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `sistema_pet`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`servico` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `valor` DECIMAL(11,2) NOT NULL,
  `agenda_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `agenda_id`),
  INDEX `fk_servico_agenda1_idx` (`agenda_id` ASC) VISIBLE)
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_bin;


-- -----------------------------------------------------
-- Table `sistema_pet`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_pet`.`usuario` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `permissao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
